# alpha-dpg
# Copyright (C) 2026 Naver Corporation. All rights reserved.
ROOT_PATH=<PATH-TO>/verl
DATA_PATH=<PATH-TO>/data/processed_cot
OUTPUT_PATH="<PATH-TO>/verl-checkpoints/\${trainer.project_name}/\${trainer.experiment_name}"
ALPHA=0.25
BATCH_SIZE=128
ROLLOUT_SIZE=4

python -m verl.trainer.main_ppo \
    trainer.project_name="lean_reasoner" \
    trainer.experiment_name="lean_fcdpg_\${algorithm.fcdpg.loss_divergence}_\${algorithm.fcdpg.alpha}_dsprover_\${data.train_batch_size}_\${actor_rollout_ref.rollout.n}" \
    trainer.default_local_dir="$OUTPUT_PATH" \
    trainer.resume_mode="disable" \
    trainer.total_training_steps=200 \
    trainer.total_epochs=3 \
    trainer.nnodes=1 \
    trainer.n_gpus_per_node=4 \
    trainer.logger="['console','mlflow']" \
    trainer.save_freq=50 \
    trainer.max_actor_ckpt_to_keep=2 \
    trainer.val_before_train="False" \
    trainer.test_freq=0 \
    algorithm.adv_estimator="fcdpg" \
    algorithm.gamma=1.0 \
    algorithm.lam=1.0 \
    algorithm.fcdpg.alpha=$ALPHA \
    algorithm.fcdpg.loss_divergence="alpha" \
    algorithm.fcdpg.pseudo_reward_clip=10 \
    algorithm.fcdpg.z_default=0.0001 \
    algorithm.fcdpg.use_baseline="true" \
    algorithm.fcdpg.reset_z="true" \
    actor_rollout_ref.actor.policy_loss.loss_mode="fcdpg" \
    actor_rollout_ref.actor.loss_agg_mode="seq-mean-token-sum-norm" \
    actor_rollout_ref.actor.strategy="fsdp2" \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.dtype="float16" \
    actor_rollout_ref.actor.optim.lr="2e-6" \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.05 \
    actor_rollout_ref.actor.optim.weight_decay=0.0 \
    data.train_batch_size=$BATCH_SIZE \
    actor_rollout_ref.actor.ppo_mini_batch_size=$BATCH_SIZE \
    actor_rollout_ref.rollout.n=$ROLLOUT_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.use_torch_compile="true" \
    actor_rollout_ref.actor.fsdp_config.param_offload="False" \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload="False" \
    actor_rollout_ref.model.path=deepseek-ai/DeepSeek-Prover-V1.5-SFT \
    actor_rollout_ref.model.use_remove_padding="True" \
    actor_rollout_ref.model.enable_gradient_checkpointing="True" \
    actor_rollout_ref.model.trust_remote_code="True" \
    actor_rollout_ref.model.use_liger="False" \
    actor_rollout_ref.model.use_fused_kernels="True" \
    actor_rollout_ref.model.fused_kernel_options.impl_backend="torch" \
    actor_rollout_ref.rollout.name="vllm" \
    actor_rollout_ref.rollout.dtype="float16" \
    actor_rollout_ref.rollout.response_length=1024 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.enforce_eager="False" \
    actor_rollout_ref.rollout.free_cache_engine="True" \
    actor_rollout_ref.rollout.val_kwargs.top_k=50 \
    actor_rollout_ref.rollout.val_kwargs.top_p=1.0 \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.8 \
    actor_rollout_ref.rollout.val_kwargs.do_sample="True" \
    actor_rollout_ref.rollout.val_kwargs.n=16 \
    actor_rollout_ref.ref.dtype="float16" \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload="True" \
    critic.ppo_micro_batch_size_per_gpu=8 \
    critic.grad_clip=1.0 \
    data.train_files="$DATA_PATH/mff-lwb-10k-seen.parquet" \
    data.val_files="$DATA_PATH/mff-lwb-unseen-200.parquet" \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts="true" \
    data.prompt_key="prompt" \
    data.truncation="error" \
    +data.seed=42 \
    custom_reward_function.path="$ROOT_PATH/lean/verifier.py" \
    custom_reward_function.name="verify_with_deepseek_verifier" \
    reward_model.reward_manager="prime" \
    reward_model.launch_reward_fn_async="True" \
    ray_init.num_cpus=14